### PR TITLE
made the header stay at a fixed position. #36

### PR DESCRIPTION
**Pull request by Ericchuk**
Made the navbar fixed to a spot a the top and also created an hamburger that can be used for mobile screen. The hamberger menu contains the list items.

### CODE REVIEW

**Review by Diptenusarkar — CHANGES_REQUESTED** [review]
Mobile Navbar not working perfectly.
You need to fix that as well.

**Comment by Ericchuk** [comment]
alright

**Comment by Ericchuk** [comment]
that is coming from the javascript file called hamburger.js in the website folder

**Comment by Ericchuk** [comment]
> Mobile Navbar not working perfectly. You need to fix that as well.

done

**Comment by Diptenusarkar** [comment]
It's Is Not Working for Post page 📃

**Review by Diptenusarkar — APPROVED** [review]

**Pull request merged**
