### PR TITLE
Added semantic Tutorial

### PR DESCRIPTION
**Pull request by maida12**

### CODE REVIEW

**Comment by Diptenusarkar** [comment]
Check Our PR Gide First

**Comment by Diptenusarkar** [comment]
No, I have two questions how does someone come to this page if they are on the previous page?

**Comment by maida12** [comment]
I added the links. Can you check again? Thank you

**Comment by BLSowmya** [comment]
can you please tell me how did u fix this error which is showing like this when opened through IDE
image

**Comment by maida12** [comment]
I guess some tags are missing in your code

**Comment by BLSowmya** [comment]
> I guess some tags are missing in your code

no matter which file i am opening its showing the same error on the head ...can  u open from ur local and check if it is same for u as well?

**Comment by maida12** [comment]
sure okay

**Comment by maida12** [comment]
Yess. It is showing same for me too.

**Comment by maida12** [comment]
@Diptenusarkar Hi, have you checked? I have resolved all the links issues

**Review by Diptenusarkar — APPROVED** [review]

**Pull request merged**
