### PR TITLE
Created html_entities folder

### PR DESCRIPTION
**Pull request by khushpreet-007**
Created html_entities folder including 404 page.
Merge this file your repo.

### CODE REVIEW

**Comment by Diptenusarkar** [comment]
Are You done?

**Comment by khushpreet-007** [comment]
Yes I have done

**Comment by khushpreet-007** [comment]
Hey there !
I added it on front page on this website.
You may add accept this modifications.

**Comment by khushpreet-007** [comment]
Added back and front button in that web page.

**Comment by khushpreet-007** [comment]
Edit button according to your requirements

**Review by Diptenusarkar — APPROVED** [review]

**Pull request merged**
