### PR TITLE
UiUpdate✨

### PR DESCRIPTION
**Pull request by ravi0900**
## What does this PR do?
* Added relaveant icon to Logo_top, home, component
* typo compunent to component
* added matching color to html logo_top
* replace ℹ️ to study icon and message "click here to open" to "Learn"

### Message
* Please review and merge this repo, I have made minor change to look more appealing, also label this as hacktoberfest-accepted.
Thank you.

### CODE REVIEW

**Comment by ravi0900** [comment]
image
here is preview of the change, everything working fine.

**Review by Diptenusarkar — APPROVED** [review]
Good Job

**Comment by ravi0900** [comment]
> Good Job

Thank you for accepting pr,  kindly please label as hacktoberfest-accepted

**Comment by Diptenusarkar** [comment]
> > Good Job
> 
> Thank you so much for accepting PR, kindly please label as hacktoberfest-accepted

Sure.

**Pull request merged**
