### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by Hallowdread**
Added the html block and inline elements topic

### CODE REVIEW

**Review by Diptenusarkar — CHANGES_REQUESTED** [review]
Tale a look https://github.com/Diptenusarkar/html.org.in/#how-can-you-contribute

**Comment by Hallowdread** [comment]
Okay, what do you want me to change or add ?

**Comment by Diptenusarkar** [comment]
As I said have a look at https://github.com/Diptenusarkar/html.org.in/#how-can-you-contribute this doc. 
It would be best if you had to few things
1. Add a home page card like all has.
2. Add next & previous link
3. If Next is not available use **/** This. Don't use **#**

**Comment by Hallowdread** [comment]
Okay then I'll do them

**Pull request merged**
